apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: notifier
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.0.82"
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: notifier
    image:
      name: vibioh/notifier
      tag: "202207101532" # {"$imagepolicy": "default:flux-notifier-api:tag"}
    config:
      NOTIFIER_LOGGER_JSON: "true"
      NOTIFIER_TRACER_URL: http://jaeger.monitoring:14268/api/traces
      OTEL_SERVICE_NAME: notifier
    secrets:
      NOTIFIER_ALERTMANAGER_RECIPIENT: AgCu/j0Nbk4Twfr5zid7VbclvYSmgBkRukdfjkzp8HOB4u/Th+H+xmQC36kJ1PGGjWI2mEe61i0m5W6O2F15V7k/zkxF4QaAXyXKS9V8goOlC75hLjkHks4f3lJJfYx0hRoAiLIIR4FNjvfz5hSL/DR4FOSjB/8b9NRQHry0KEcdPRa6lylZbCnuzDbd7d/jSV3QZ+S5dSrn/W+4OeaSC/1VwlQ2h8fLajXo6A4EBuwHNGYp0RjOfpz2V19h4pC5OY3AIH2/XsQmcTh9ZVE1TP2BubcnuRH2KeV0jXbcCrUDHW7LJQeM/YMEDobbS0YZdWWeDBvBmzBMHJlszSxwHKpZYucxxV5rNGNFxXgejuKOjrSgk7Oy+ma8ieiI3l4ge0VCOyUV2P+g2/L0si7zmQxJimtd18chBvLmAbJaokz0qQhswFPlNRfgv3Is2YMeukQEwgyB0cspEFuAKEUcakizxgij316O6TI6hkPozKlhsAJ4mnxghShuYq7nfLYyw1tNnc5q7I1NkFwOGOlcyQZAznt6fShGj7IcrCLVf4HQYZdv1d0mabe01IO7DvGHHKn01j5iDeHlh+MQc+pwaWeC4bU4NO0cK4hYLZWdln0Zr9zQ/TzLoPpV1QLITT22dDUaf76Xi5sDKI4voHvlCokKgK4T13nlgxUns4+tDwX1aiYoymnd7fWk/bCQrugelkOr/DbrQzarfCJLv5Ul
      NOTIFIER_ALERTMANAGER_SENDER: AgBmDJu2X0Tih6vRjBngidRYgqPyIob3hBKslqhTDuqOWMKrnt2prqLQL1WtMlT9Ez6XOn0zDuQRKUFVejLQz2e+iT30ahVsZJnIPWczWFDj8unvZcH30QnsV/JDtlmYW6JbDoJP3qHlnKQbvRSEVIsdesuIsQfLI0BNXaxM5f90RlkqQAiEC+B6BiOk/yJCFyQv2Ft8VuA3cTMwfqN5TZIRB1IFcElP7jgqPRK1y93Icp3w40V8ndCdVkO4EzV+tuv1cTg8gt3XKmkDsjojbY5tzS6u2TKNEG1/aeY8+ifUtOynuxK6WTHtOSBV2g4gpNriQA4G+ivNOkswmomfMd1CidTrLiUlb6mSTyCDCOjN9/hSU3iUOBu05eYTcK7dl6bFqgNsahzPqDz1ko1FX+w44H8mAMxkLNNMQs1SFbK+47LgmUDPu9rEy4tVAygcB6j1rcd/08a/YVMJ4kgr0n8RrPGg7gT0vrapTQ+erM+6gFmI7ZvHUpWgavYSpTAX4UVngyegNhvijcdYuVpYGPgMUiD4YvHb3ibTK/pdsAdS0pOnyDoKI3R9+QS7TPg10N7NWMEp8IDm/HIa8nJH094vtsR+6+hVAZmKMxE2LV3KRSLLlQyFlOYFF8+I4DHP/Fw+cR/AXBGamp8W0xWn4SehgMKvDHnneIynElfP++KzdneSC8bxSPC/TID+bpPWNeEHXyKHHgnns7X1yBKZICRnVB3kciLo
      NOTIFIER_MAILER_URL: AgCRFxPgz2hCTSl4zcBghZHtOsSaDTRaMRsmrGaHqp/poWfBewt00nw5SZ7djU//U4zK3chlyljnpijvfI2ZuG5pCAaoQiM/cZMB+vy4fTjkErtGiv9cqhV25Dd6K9WNvcdnBss/vkuLtHXCrhgob7GMUJXdo5iBu20J+lcyoECDt1h0+yq83Onfm2LUXBKDBgfa/wtPyRAFSgrt8qPipfUqnzt4ZnltFCnnUUtQml0kxFYQi0dXig4Ri6c06veD1rBsOyIbutUgUWQ8JOvc1toXn/zgRL5UISfMv/K9CBkb94SZUVWb26Vb3tHX2lGWoLqTLzc+KOwmvHOY3s5RJPjwv+hUPpsTrcfzTOoznXaFRf759YEedeC0vJJRoCtwL6v93gVrvIFs6bVkI6fx/M25mIOdpPbMaM+c8V/4crR2D9OFfpXDtXj4QKxbRyl7YlUqKGvm8zHK4/oHxi06MdoPd07hp8orE2oMZJZEvReBzEGLWKIKNBaxwyVqRjMrZkJtb/BtrOhra+NQPC6S6/Aotm615mLYKQ36GkNDakofwlVuTSUkgJYbDvM+53vaulqF5oYej5KYamtuzg7wB5AKVFLqNJBKQiWOzNenfdIjWl4vQVgmKnCKC8nxYf3RIwxbuuQeFC97rMb/CYYIF/855UOgOuQgOLLOVa6K3szuJ7K5GZ3j8S4IKca2U7m/CJOkQUGNF6qFZqmUpUAwd6fY7TVea7bbJt0OmAgyCpRCRw7Jir/4d9dmMGzriBBUCi+pGu4=
    ingress:
      enabled: true
      compress: true
      hosts:
        - notifier.vibioh.fr
      https_middlewares:
        - notifier-auth
    pprof:
      enabled: true
