apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: notifier
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.0.80"
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: notifier
    image:
      name: vibioh/notifier
      tag: "202202131001" # {"$imagepolicy": "default:flux-notifier-api:tag"}
    config:
      NOTIFIER_LOGGER_JSON: "true"
      NOTIFIER_GRAFANA_ADDRESS: http://grafana.monitoring
    secrets:
      NOTIFIER_ALERTMANAGER_RECIPIENT: AgAlCdFmH5o8XumdlxG0NUeAOMEU5rFNNa89JH+ifn66sc9J2Zpcud9aiP4kHZyKh4WvnuESWDyr+lYy5p5AZF/PbOTLY4KeZE4Id55/8rzPyUO9z14aetuOI/yMiAsp6+Z224Ie/xrlQT/qeWP1UwS7f6xibRJczf5NGdDjPWTufSy0yMnWOJTMGP/8PELJDrnCi5bmUCCnS8IUyAd5FUAae/JMQNlpoWccNYhhe2DyD7kMfgf6q/vbZ9POirLZzleyoZGBjX6zbSwNi0HOlFVWajRFwVGDbOcler0GG+nElOhZehUyQKuNRn5HlIdGXwbe70CHur/BVNclz55jkwuZQ+/JivKxuVdrrnT8p9LCvNsEeX9fvQTSRopLlm/FTAxTOtECnE1Cc2mWZ2l2vGGrphyOZBPMgO2khUUAd5eUNAKykR4zrfzE+lP7CChBJQFbBTrn30WgR0Vxp9CAM3W4Jrmb17ximKzD/r8H8qLd1fUVOjHLYwkDYTPxTjXRxzhFywhxMSamwLHxl09wf9RpXtLU8sxI4Bvq1psm91a01tRi0/mp2dsFkUuOhppjoi4+j8OF/fnOu13GOlm45CapPgql0C5CVl3KR5LMUNlNTKC4u2CkHKd+mEh+eQCRa4ZH6yvhEiMAd2DCrkYsnMOg+VmUCwU4q9n3T5Ip8tYRSgkqBnWBz+RWqpuhTmzssap2XXohSIpqvQQLazSn
      NOTIFIER_ALERTMANAGER_SENDER: AgAma2Jydcdf92AD9ZDtwco3ZGMCcg7tD9fmMG9MB9rBp4Cfo6ZSxADKooMLPwXyhJYIBLD9JUpExEtQILiL1WPxzReP3OgoPXlpn81daqRo7ZNvwiVnyDZCF3UBe2zPWsiCpLL7UTheSWzq82gSqPuLyqboNTU7ewK0u0SC1lC7rVn2tmrnjnSpYAf1vZ7j1Mcc4ohffI23/B83vEZrlUHmHylxFwlrNx6pagJjA7uYH/+CSgta8yscTErjpHzwkZPIwbUTp/j+PdvQiS4OP6RnCq/pTYsgySWrjDrtdYZtjY9ThsUSMGGnfJhAUF8oXdqQGl8KuP+w7M//AKKyBvfWK7fNrC/esTzYX2hrB3lk3u+Iyw2eO5IBPuEFIQLeKOulEShEZsW4pI2pzCTIHJihLyJM5WwDVF4U2yIKFg0uuNtMQkePJ7H/9C9OeDoTVmTDHnYf5R+IdlYFN6jPB6hV/LQlFb/BMQuakT+Re/u77ERaNasr80OMUp3asy5u+P2WK7MCxuH8yleuCMZghf/kJFDLDxO05wuQc9igt+tcpX+ANJc2gpxjAqgbI0DTZh3Qb7jLXqM4J65/NIR1ovJYGKPsb8ap06Ti6zfFeylgmQFD8kH5HqEcTDTcPlXR9tHFQl+hPaBGzE107msEtkCS5z/n82qMW0+7/suPEL1W9cjQY8DuRtnJCgQDCBCYWwtW52Rizt0XijHCkx805WNVOG0HC7es
      NOTIFIER_GRAFANA_PASSWORD: AgAocWwTKP3/RoSGwmk73v4bMxkZEtFJfFp5m+J6hqI9FA+n83tFFCFPOIEXhNkrQ/ui8SiPJBgVe2EDBcvCVQId9AOascu9BmbssOwW9wN6GSAe+XXw3Qp6UAvpLNDlWBCHaM8mEsW6Bpx7TTNxcK1zo5qXiGkxR4u00LE19aiery7JJaWc4pn03bUx4giLfpUy06t7zlv0iJdlSK+Y5DAlocdU5JCQYQg250T6RxV1I5vGoLlgb5XzKolIwTQL4DNULEVFysoby2MJEPPLJypsiAiV8X4C9KjxdRaSgNgSFIsrP6nsdiwWh0J4PGXGk24QE5mVZa1THDtDM8dImZvsg4q1fyhXqpTIOdzgPpldI1vRINQ/DkSKmfxeotVh1X9EZkat1bWI5U+5WHKOkNMEDUBk/Snws1lSglBTMrvqbifBdxptMHOvI6jxRZYpexFeNRJeQMeb/Xg2XxPsVSplCFHbUad3vEiagRmYs+LdLP9dHkLMeWPeXWMtrAcstvlBW8KkaNlBl0MPI2UGkCKl0z5TsSy+3s0kMkrx/HSE3MpDrpBjsATdiWlP6FgXP1aT8xRa5YA3u7wmB38J7Yzh7TLVbBf+TV5ICFENWED1sh9+gRoRPrY4zWA5YJQ2F3ISdw3M7Ws0kY8wUyUDE8gN7lecVxUOwu0WN7lYaJ3syPjuNdJQ81JBvlYdlCofO9/lnEyZurRm1VgEOdWZ7Q+GkQ2BlAoJ2WjH
      NOTIFIER_GRAFANA_USERNAME: AgCMrPLmroIVoQSNt3iwXJgT4HRO9CfosPqgRLSzqS3klLJmBBPJIHpCe7lfJKXP1ozBQ2zgGTfa3IZhArvsT3658k2NPFR5D/U95h61aybGbYq1GUkHL3EckpWU0QyucgQHOSNUPJHUOA7LnpoC9GkXxp3tRvvKB09olW7ntKkszEs/c5EAalwjivo/locZH5iO41ByJkNwaRHu9Zn5AhEbAGZ88/ei4Uyxaly/xyiTB/ZAN01SVnhyp1iSxMb6AIYHDbB3GPYH0+oVir97axEDlrxeAuR0ncOce8ga3PRZe2YMR3c1mbLg65wJPBD9hLRK8HrLKjLNamwASJdtYA8Cs2YiA2M6yiu5CKVaAy4lLX0Xln2bkqM60y2p9HF0NAOvu1XJMjswyUVJYJYzMyQF8K67xgYurdlb0kf02uluZUnEA3vJ7tFbucM30SL0H5p2KfXmWSFtlEIvZB17jWKpiMjxF12LZB3NFk4UY1Es9s1U0MXdFHlLw3rbVbBLk5btUQRVnps9TVuzNUkBaVxQy1zCWkAVKj1sLd0spd+0DGnPpEWEI3AGeGyvwZgSR+hY0n6GFipxlosCE99cTiRbqIv4BevBAI8Jy4la2BPmyF+l+P4hROoOuCnNMfqXxMdsG+iqleisT0bBpYaYOoJRayNidpk3Gvw555HxSfSsy6M2n8m4kUldyCebc9lY0HYOTWOK+Ek=
      NOTIFIER_MAILER_URL: AgAhe4uzhzQqIFNThpIR+hnyrdQ5TbGrj1ZiJm1QunZ1edW+h+oXr2UJQ5aIryaCjjlDd7cbMorpMwJXQNtqyNSYdz18l8AEfgz2R38hh9cOtvZIdMzmKoXo1si0tVLj6BPmEPdXg1u5Gegy1D4eDEggZaavAi/5ZZ/CmRQr1CGiWJzeTXbd9cIAYUDfq9rOyGY73vX8Aeh70v5NsKLzpTgJ51IhBWx0glgz1tlvOelu7w2u3x+R62bRh97wc1mtWurBxsEZY0OFc8A2PZHQ9mBfVsyVYfvqBiPd3fCtO+4dfY+cS80XIuKSLqg1aKhxPBhmdsccFXNFRALvmSyc7jU29KzthbUmVZ40ETEbIy4NGvYCUIyCgDe75hrOFmCNFL0/Y/1R42J7pLHI5PM50fpcCcYmlhoOWREY029F7iIDqwBIbZBcKXbc50q0R0TERyU50bqpFmX3+svM35PlijXzES87yloGcTs8vf5C4ayihBTV+UB+udMLTtnYskT7w7diybjfvI0ssQzsbVk0tX/AdFG62gKld8zWqdgbcIzcHEY5guLbqmC2Qo7/HopQlFErNVtQ8oNaJQAXGe7T82xacUIWvlEFyFiql0UsRv2lUXILgM7+fkD58TCxdDOVk2XSCMRECLnu7RtiuLq8cs2GWWPL1F+SLQmfp+GuG+b2mTkKqgqzFhrXF3So6E8J2I7s0MNSjNZFWhTjdvQJljW+ukjsIIDXmL/XCqckvHHefZZ6y5sso++XxcMueKyiLK3EORE=
    ingress:
      enabled: true
      compress: true
      hosts:
      - notifier.vibioh.fr
      https_middlewares:
      - notifier-auth
