apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: notifier
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.0.85"
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: notifier
    image:
      name: vibioh/notifier
      tag: "202207282031" # {"$imagepolicy": "default:flux-notifier-api:tag"}
    config:
      NOTIFIER_LOGGER_JSON: "true"
      NOTIFIER_TRACER_URL: http://jaeger.monitoring:14268/api/traces
      OTEL_SERVICE_NAME: notifier
    secrets:
      NOTIFIER_ALERTMANAGER_RECIPIENT: AgAXEZ402zArW7yJLRJ7rHvH7UGqw2FBnX3nYh7MYDS7hwcNKSL57RkFcnGd758npw9f8iY0Ze0Am+WBcVf0EqX7cpoAJVLPSpVQscbkqfQAKWh9nYkFW0Brp6cY+4dl656zC6fprUx0vGw7PiDPFZqmDAN7cF3SH8FYw46IrqFzhTKpDjVHsLKNS7QYYgg+EWIVWLhUjbgg4VZRCNqIzaR+z82mnIfx29axciasxuqubRheDTOLBPUhfS99Hao1o5B563Pr0CTY6yO4Ly28+L3XGmv4U0BRNAwH5QuxrJxL54S4GvNsTVjexYzMHEQMCPWHfquxlslmhZ0RKl9DWryh3OLzPDaRlgul3NxIEFiGYeK5Zb/Hx3hkK24kNsIQnoys+M8rmkl+wnYNBt/jDYmzcT/Om3bENX8I4dLWn7mwjS2+YRBqDwGPfbS8oCvek1mDj6bEIN4jfBD8zeIMv0VN72MZOf+7zS9OPG/snp2rmeMnvd689a0Ql/dQNcZoNq/AYUr7Umd1YIsPcjr5XsHaCysifxDIUtbA1L8c22l1Nze29klvov5taWkilGw1IH6bSRP7MH9hi3rU737b6zv7KcTG6g+I4yIEB0Lwmlm2x/vPOdPiLUbJqVa7HOxEMJjBc8RnOik5nWQO1HSYE63RXzVcBrMT9gpOvVW9qIQS/G6IIihOogHh51uR7sCEskIzADmWqvfIe8KPw7JH
      NOTIFIER_ALERTMANAGER_SENDER: AgCkTwqmylKBQP1fxJvio0mgEe2qH2CcP7I819fcYsZKPBm6TPCcr8L6BTxuxh6gJNm6xPBhdcUutas9G27bYeUyVMFcNA5NEt0kFkOn4MET5ulAY8yjVeiwz2sAW/xO4UItlRKqv9ef83HFTBtyOxeb5AVdEndjGEqjMsQJG2e0HwoqCX6f0g2ri5r/RIGMBF00N3oMI3TrfYxUKPzNTKXvEeqIU0Ooi2WybOkO9fTEc0WURZG4G+srQngAok9VjsEG4YTbjmPLUM1Hh8MlA8CimYI6G+3YHlymkxvlKslSU9v7NeIoyMjpM8v2TsaXVeJz9LuMG6MUmN79fDVxryVM8io40PlC0qoG7ivaTGH9hoabPfoo4cWnp329Noae6OPt9wF2TGqsAQrdLrw2wD7NfqcWRoskK1lCAUJ7uxucLNE+nPmQlTulBJcrmcDa+vQvBPnsJhNOp9IFkD7tBlsbf6WVeMzQFW95GMJJ4yVAkKCrEqx5iYzgoLyR4hTFN02UJxjonztpXX95fypW0M6IJHX+CVqmiNAbjqjo42FVptXI2+G8Q8FjFhGHdH8/04d5lGGAAXIP/BIc/GrK3V/2G79u/ecaSy+JlLtYuLYr3IDFuqO7374/X3TeDmKt6zrCGdhdFHseWBXUEVFgD/g0W1yO1Acz1BkrQ29W5I5grGK7Ye4SHndrQ/zQdYw/BCrb0pwfgFhaV+RRlkRkLOyllmPaCgMN
      NOTIFIER_MAILER_URL: AgBwD4cdnDyfNGHyr+PeQ1GnsZRVIbpV0vBDhwYeHGc3uxa54JVlqRLU3Scaq9XMYDzU8Z1YBHK7VRvjToOpH0cpV83uARpG7nh9k7ga4b4nowb2nY3o7LNHz2oc+6CbUaghgbLpbDN83X+b6SnsYMFGL7ZV8mWCgBbw4DRZ7RFGosoxwqFxxIS6/JJhGZuPVHG8og2PjhyDJx5z5XeoqzVIGks/lzkzoG6uklI/ssZbYVjc5fOUuOGrNLX5bxEPq+Mq7w+caaicoG8zsp11SVRXhDQ8JAu6XDrqg5JJLLi6TJ0REHIp91cuFEPD0Cm1X2joa1rx/HBghJFUsdAZjLgN51OXoIpTnoz2L4e7guNWYZzcY1wcljP9wcUXzF3ucL7+wOASZsLTtBnJzdyLkeLrH+mQ0xLreUFrow2K0wzy2UX/fFtplXZ/G2F/uEH5xmwmA+j7l7ihG1+Yd+VUKfuoQjuUw0T1zZ7l9J3QnwZ40+6RG83h8bfWBC5sTX+X8ke0o2FxmEmHhWfpcvOXaGdZDvN7NRRZvuSXmnIyEWaiwr69e74lo0/Tw7arzdaafaH0Tq7mQedmlp2RKBzomao848E3VLALuu5LN68ZOCCNVgcz63UcUyUsca+J45zxa70t9LBtO59Mj/RQXsWIEiOVcxdhrtjUXx/f+ohibtBFbnelkcXEg+Na+ZSr7NGZS54GqR57fjMldwWaEvGxyZguDrAXByQPaysWJ/OMDJArhGjFpTHFPEYpz+4P4WuKpAO6hWw=
    ingress:
      enabled: true
      compress: true
      hosts:
        - notifier.vibioh.fr
      https_middlewares:
        - notifier-auth
    pprof:
      enabled: true
