apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: notifier
  namespace: default
spec:
  interval: 120m
  chart:
    spec:
      chart: app
      version: "0.0.84"
      sourceRef:
        kind: HelmRepository
        name: vibioh
      interval: 120m
  install:
    crds: Skip
  maxHistory: 3
  upgrade:
    remediation:
      retries: 3
  rollback:
    cleanupOnFail: true
  values:
    nameOverride: notifier
    image:
      name: vibioh/notifier
      tag: "202207141430" # {"$imagepolicy": "default:flux-notifier-api:tag"}
    config:
      NOTIFIER_LOGGER_JSON: "true"
      NOTIFIER_TRACER_URL: http://jaeger.monitoring:14268/api/traces
      OTEL_SERVICE_NAME: notifier
    secrets:
      NOTIFIER_ALERTMANAGER_RECIPIENT: AgAKmc4hIivoI1b7XgWoGD2iPyGxY+0sgi26/dUH6qw06o1pnfr9B5bS2P1aO4eHiL5NfEnWGycrZqetua8pMCLlMR8oS5dDbXra8407s1OtSFkK7+dpKtzCtCJLZbomhHF/CdtzxMwhXflPDp34fqU8jm0hwS590V/QghGqfUjHq9Rimu4q0K3QHkd3mOKBJ1i8mqWZ8UkLu631TewcvWUWRKIyl7umAkkRj9tRxNgIlmuI147gT8CwKKnZePd0EUOYGpDVbosM+2MZABnfAQztsl+pDdEhdrloz8Wa+7wQBK3Zk+w4VBn2ZdIB1q5Hrg8N54AepSPJcXASo+H3uM8fDZ64G3m1/dy6oQtkeQ8BZeFLCg1/Uw0XaV7HeIbOqfMCWQ2XVYa685Jf+9JXS3WwtIHGGUXXM9w8mOr2fqlgtzKrClWDIFl11tknT3LwuJFbijpCpFgt/abLfLkA3seEePxpmS/SB//I62ccJ7lzdACpE0E4HM6GEvVwgpUK01VRosTh4WihQXgDdDlFp5Na/LJfjwQi1TnRdZctF87UC5mPSDnUST9HXwTqfT2YiCAkl4wEWBn7YVgganjnKezx8CZg8HyRSdJ2mF7QU1P1uVfRsDywpH+yBjMOV4YcBztDDMbCwco0G+0gGcBjw4+QR3sgrYDQY/2wpzHqddmvsV4Ba+GIHzU4cFVGF9tcHAgv4nGiC7JTHEdGI9QU
      NOTIFIER_ALERTMANAGER_SENDER: AgAsDwXZ4KH1uqj4+12zYA0NXUGH447zwCwuOctZijw2Kr452Uw6D1hSShJ9IB1yAXelqjDREMiHkxnmutwDo4whYT/wGnaDwtmexS72P4rhXeeMpNOKV5M1dUgN5vhRfhwHaRcwGS+a8gOCX4FqxVqXFJyvfbJnRRI021MThpBR1fgkXnd3I/KXHLsgl5gbv0F/YYb8zBEw9R/9MnlnmWS7r+hVxsPVK3D400kIAX9Ox6l83Kpr85zCxJIY1gtq5QDgi/AB/fwc+ZIKKGYifF82qa+IX9eWruMQURadR4nNjrMcOkKNCOTINU0Y5L49pnIno06n5tiupOryxwuQw+7ClovJjmG06Remzh2qmpKtP2pZw0/joZAwquY7iHygMiKilKN7luo4H7jlP7thUyrxK0F5l0m0miXaShe6rxYDn8eYndMXCscqyunepmCkhICMujAkNLZWhvYdyVostOExTJHZFeS0iKSGiF7HjClcURGTBPdNR+K6TN+KKZTXP7sv3+Z2MjrW6NrHr+Zrip06G9bmRlVUu8NbOvt/bT5pc3kOwcbDg3M9HSogECF5MJh0hQUYk+X5REBsGyalwGHoM/AmCDKdpj0cV+aUu6I2V9i2a6LscZ82mQNuXQMyRLBDlFNCJLn2/jczRzx/FlXSLsGy0W2J11QPSJBOoW2955yZh/68EDwEmq+YiBc+iYBH+ixITFtLQlPq4FMN6VORNkAw9hDT
      NOTIFIER_MAILER_URL: AgCncPS+4EWe3E3ZQ1GjEKpeZHuH87TG0wQBY+iU6zfFPL91KtBRMc3Mk8d2LV2KnYhRor7twLjiPGkVKTv7r39t2NKUBUZMqigbOu6LwzSFLPK8JYgCmj8TDEGrLj/8XWoq8HwI3RLUxx797Nn0A7ZMki7pOcIKwLlvnMTmNqYH7pCc4GC7G/CS8z9pqF0Dmc4LJ/1QRDC1pSgEQ+yzY5dh65GHUQhF2dxV7G2JtnKz9Eb+kfCwRYqRWae2ZuyutOctqVg54FOsHgC+sSpk2dO0fNuzH3DYYBMoAIu6rbyboKzlJJlN5ol4mq3B59XEh8x3Z3zDsBvSK+ZfFCmAqDKgddP1s5M64exlirbYaUIDv/JZG5BG2a+cnRS0+asWJ3PuRCRR/zUtLSoBGk+FWDBMrnwD6fLsOyvGqzCG7KnvdHn8v0g7zqz1yudnVBkA6QOvKvcPJeU432CwjOIhiSS6LjGo6hRec+J9h87OU2U79J5iJivtGr1hCNBBKMMupevB8is2ZlzIcGToAXPezS0iI99eo9hYgL6++EhcaHIXEgtRJj/EagDzLIR0gkkQ+nW4iJSlYp7N18C6IVjjdIqyXtfnqfpmVDBsfSifvKUwNJjiayBKZ31zqT890yf3zINLqXqpBDbMwbqeJivFL+P0FogdENPIavrgJzAMoxoKAi/58TUvK1PqkfjlAAkUgmMJBWSeERixiqyUKvkLsJOT+KPnfoR3EXQ65n6PQ+uMyg2leMRI82OggUQ1CuqBP5XMDdc=
    ingress:
      enabled: true
      compress: true
      hosts:
        - notifier.vibioh.fr
      https_middlewares:
        - notifier-auth
    pprof:
      enabled: true
