---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: notifier-auth
  namespace: default
spec:
  encryptedData:
    users: AgA1pb7CamKV/qE8noE69uxt/iBA0xT9oic6qiILngZi15+FLBKSOJf+dnbf+tHeJys69NHFnDVrw7VFqQklxkGknJWFcuQsaA/22gb3AERkbIF/fK2gpbiW1vbN/QwMDzBi1oI0NbXhBXgYFJ37Zm21A++xgooDWjR9fHrnZfAnKZ7f0Th8nEPSxc6WC3UFqwSHyrtGxBtI7tu02Ng/Thtz4+Xb88XJRD8b15hyBAE21h4slAmU17f8NqAQBtywDRr+Fd4Sg1BKllW+Q966EruMipo42l2eUQ/W6hSmfYmGhO3iRDUbLhbEgq/0aoRp7aZ+JYkb6uJI0m9NmysZyU7eHVUFjg/xUDZsu2BWshQXHCFhccRFo1CHj3c0K2PyoMWPDbOMzW43BAqTVaD8YUhWhHZg846EMncAlvuvHhCuwW680KgEnXaCH8XZjzZ9/0rIyatKjOuZWmzJn7S7JGwwCIjXjObDeNrirqWZnRU7/8dQOcAUgISR2MI5CHJ6jHYf019rOTNHtnzcOz8qeqms8tOLGKKXtEt2gv71ae87HTBd7UBVZf+GAwOaeoJ05S0w6aLF7bnrhaZq97kP+uxesawzHkMYLLSDJxbKxbFDWVCsdlZbBXyS5SaYyLoCBdEP73bPU55bwW6hAhksP/HNxLSkzPSTRD0f+5vRVfBrdSSNBparP/ecBCXp1EyycvYUINOFBXeIJRQMxkBURllmktrlUL/govFjsMu5UgoQ7/hVLoUJAfexHZzlCcpkxRwcwEinqbdeb17F8TrAhuA34fCS
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: notifier-auth
  namespace: default
  labels:
    app.kubernetes.io/name: notifier
    app.kubernetes.io/instance: notifier
    app.kubernetes.io/managed-by: kubectl
spec:
  basicAuth:
    secret: notifier-auth
    removeHeader: true
