---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: notifier-auth
  namespace: default
spec:
  encryptedData:
    users: AgA1pb7CamKV/qE8noE69uxt/iBA0xT9oic6qiILngZi15+FLBKSOJf+dnbf+tHeJys69NHFnDVrw7VFqQklxkGknJWFcuQsaA/22gb3AERkbIF/fK2gpbiW1vbN/QwMDzBi1oI0NbXhBXgYFJ37Zm21A++xgooDWjR9fHrnZfAnKZ7f0Th8nEPSxc6WC3UFqwSHyrtGxBtI7tu02Ng/Thtz4+Xb88XJRD8b15hyBAE21h4slAmU17f8NqAQBtywDRr+Fd4Sg1BKllW+Q966EruMipo42l2eUQ/W6hSmfYmGhO3iRDUbLhbEgq/0aoRp7aZ+JYkb6uJI0m9NmysZyU7eHVUFjg/xUDZsu2BWshQXHCFhccRFo1CHj3c0K2PyoMWPDbOMzW43BAqTVaD8YUhWhHZg846EMncAlvuvHhCuwW680KgEnXaCH8XZjzZ9/0rIyatKjOuZWmzJn7S7JGwwCIjXjObDeNrirqWZnRU7/8dQOcAUgISR2MI5CHJ6jHYf019rOTNHtnzcOz8qeqms8tOLGKKXtEt2gv71ae87HTBd7UBVZf+GAwOaeoJ05S0w6aLF7bnrhaZq97kP+uxesawzHkMYLLSDJxbKxbFDWVCsdlZbBXyS5SaYyLoCBdEP73bPU55bwW6hAhksP/HNxLSkzPSTRD0f+5vRVfBrdSSNBparP/ecBCXp1EyycvYUINOFBXeIJRQMxkBURllmktrlUL/govFjsMu5UgoQ7/hVLoUJAfexHZzlCcpkxRwcwEinqbdeb17F8TrAhuA34fCS
  encyptedData:
    users: AgBQOM8m5RWP7p7HaJ2DFz9WG2F0Hm2kOURvTn/UwhmwNkEm4uPejFVIRsP4HMNmyUo1yLWzLIRJ+OAhiwbV86x3fLgbGhGU8VnKB9Fwfp5IR6SzZbjzbEFkxReOVafLWi0bjVKSN0QOmP6+8XKo9J8/Fg+VaJo0YE/aP1Kr+Zgt11XF7vggxSkVd4r4mBww8pkqPuRYQSXi/OoM0TuWBuHbFVFE26mDMj50o30VzfmBGl6ZzWWA7C1QTHxbk8KVX7i/gmE8s13DpzKmPVZLdtjA17ezg/Wy0mCzSbo8mJzhdke7FIQSi//6S3UAgN/hBFdVEd5S5K7T8ZWfGuUykdNsOXswWLxoZlKOfHOY/Mt7H9ax0ES5l03cnf9Gqls34XJ0MJB/9kSipNjgH655lMF00eENyTMAY/Q6DM9iZpWqwtt54lpooRJVJApmRsu2so8FFU24m5l5EHsPQ4FrwfHJzbf1mPc9cJgOKn4E63rM9HRM5LzVUqO+JW5iQepPvdsVakGnM8ZGnKS/HX4cpgC5d/hevdObfpgXmJi3XRo3emJBNOHKZTfqd7MMSm9JNJw7tc2BiLhHKmlIwFCVJ90DcXJeDw7jT/r8xj3M+tFurehS/oKd+KNYM+aeB+S4css8eEUn1iQO1zFmsIydyWl+Ch3bzoEco7Of/R/k0XUWcHB5N04WFxd4oZOMU9zxyxCd63ti4NLE6qWc8M7MTc0Qa1BYQIQkSxoKtwHZbfZTe7hWpErGp6PgBwubVdGpEF2rupuIhUDhP5iX37cX8AusdQQL
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: notifier-auth
  namespace: default
  labels:
    app.kubernetes.io/name: notifier
    app.kubernetes.io/instance: notifier
    app.kubernetes.io/managed-by: kubectl
spec:
  basicAuth:
    secret: notifier-auth
    removeHeader: true
