---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: notifier-auth
  namespace: default
spec:
  encryptedData:
    users: AgCkKL5jkK55DcNFIDnFM2Zygwo/TqKvuTBZXhFD6qEMOAi0VJ46xxr+uSIZ+7CttnVDP8XZxQYFv2yMNH0BzMh1sy5VJChFzieebu8aAaLvaMRkYN3L4Sd+DBWWocrkLyvEM8yfzLOQF/6Nk0wnQNLAQ389G5B+Sm5qnJZMUiLsaz6YxInf7l+15nJCQF+yGP/6qKh1O049BOtC8hdpNUKxLJsUnqitS/xRq7Od7Af+AImbTggw3G9BXfv64H11EHitHVwEI4xo83LDFAuxUDw/ViZD6bRA5CR9sLxj7usrVd6h/Zu33mPUuDDKWZanW+Kbuj7m4h/Mi6qNKHmIzZEXCtdAnpebrzjlfSCzwnsEZNTBELqaxXFjIyluc/Tgv8TcQLClEOKT1utfynmTgHH1ae5IXarDo+L2U4UmWgcQxkTESe+fvRG0kGkv3/e1fKDND+BA6McvnAu3L8OUQ116iZRDmwfFNPsi4qK4NA9LUq7aiyAtIR+HYH/RZKcJy5wbDH1+5wq4vPD8fLIvife2Be7Ph24bf3A/slPoGltH0uMY1x6lQ7YCXJkuCdqiy+qy1YBOYxwomyU0BZaPgHE9DDFHZ52JlIpsNlGx1Mbk3m3S/MRqH07rcnHkOsfHmdcdeAMZEX/28v0N9pSJlBlfAAklW83KElFKsivbD0fNN/mEHBg0zFEAvfmAc5TUAXlfoGvtBZqSQfMjWBjxaeJx4p2ONsmL72EFsvOwp+CddZATnueIVrfNetdLRs9apEVamDMiG5bbzK+EkZWAT3+MPQWw
  encyptedData:
    users: AgBQOM8m5RWP7p7HaJ2DFz9WG2F0Hm2kOURvTn/UwhmwNkEm4uPejFVIRsP4HMNmyUo1yLWzLIRJ+OAhiwbV86x3fLgbGhGU8VnKB9Fwfp5IR6SzZbjzbEFkxReOVafLWi0bjVKSN0QOmP6+8XKo9J8/Fg+VaJo0YE/aP1Kr+Zgt11XF7vggxSkVd4r4mBww8pkqPuRYQSXi/OoM0TuWBuHbFVFE26mDMj50o30VzfmBGl6ZzWWA7C1QTHxbk8KVX7i/gmE8s13DpzKmPVZLdtjA17ezg/Wy0mCzSbo8mJzhdke7FIQSi//6S3UAgN/hBFdVEd5S5K7T8ZWfGuUykdNsOXswWLxoZlKOfHOY/Mt7H9ax0ES5l03cnf9Gqls34XJ0MJB/9kSipNjgH655lMF00eENyTMAY/Q6DM9iZpWqwtt54lpooRJVJApmRsu2so8FFU24m5l5EHsPQ4FrwfHJzbf1mPc9cJgOKn4E63rM9HRM5LzVUqO+JW5iQepPvdsVakGnM8ZGnKS/HX4cpgC5d/hevdObfpgXmJi3XRo3emJBNOHKZTfqd7MMSm9JNJw7tc2BiLhHKmlIwFCVJ90DcXJeDw7jT/r8xj3M+tFurehS/oKd+KNYM+aeB+S4css8eEUn1iQO1zFmsIydyWl+Ch3bzoEco7Of/R/k0XUWcHB5N04WFxd4oZOMU9zxyxCd63ti4NLE6qWc8M7MTc0Qa1BYQIQkSxoKtwHZbfZTe7hWpErGp6PgBwubVdGpEF2rupuIhUDhP5iX37cX8AusdQQL
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: notifier-auth
  namespace: default
  labels:
    app.kubernetes.io/name: notifier
    app.kubernetes.io/instance: notifier
    app.kubernetes.io/managed-by: kubectl
spec:
  basicAuth:
    secret: notifier-auth
    removeHeader: true
