---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: notifier-auth
  namespace: default
spec:
  encryptedData:
    users: AgBJwAS/T7waJix5oW+9qSJ3qsh8VUqHSv8ExH3jFWCq6KCc3eVkgPFB+NXd+VwLZcaIhJnSGCR09Zm5RZE77CcYBPpmGiqxs5QD0gBrIwfs1ofTF5ZZ7IoxhzZmFZ+pjhXYpg7TZJV8slKojfn/MLy26tM6DNvLdlnlApMlCjCA1Pdiphv/17OyiSwPTx7D/L419/ewW1OF4EQhSpsNlXquuai4kzQQJfPK/PYvg6K5ov9fLElbVTqGitfKaxpWMEYuwk0fZEqMA8ZLIqMpeqGUh7fKUsrztbp33uTn8OZ5iCS0cBDiXKy6uC4FD69fP647zZL2pQ8QzFEfRKPJ8Sr9MDVlHOEgmF0ePdToZ7E+iqd2ZEOyZBgHOzGJumh6F4XuWP9LoPARZuvcPY0YT4uwzwACd+GmFFYvun9RqOALGHeeXxOtpMy+I08j9ADlXhfOcioiILH7sObkNb5RV4qrZOmLEXMX3VDU9SORBExOk7p+wFJFxVtVuSBSwSuLG1moRdr6o2S5dfXmwdkDD7/ZzPzjHV6uyX/852/vB6Tvmf0mtjIH0GtRJOVTRfvVcJZUBLfiAGGuBM4WAXKBLiwwkWRwtDkP4kManaTq3STLZ/qbrYWZZZyQIzi/2cxEiu7sg5XNi+6r05OX+TljcmAmCiyKqtd23SGZ2EnNf2/iRK3xV7MYsNfyMIPg+XGVn6kiEsbWxAHEnI3tT8/d70xRhUOqEbx+J7Z0vonka32lmF6aHWpkiJeO1sNeYJIdgp9+cvsGjGCA36A0cIWR3CZa1cSV
  encyptedData:
    users: AgBQOM8m5RWP7p7HaJ2DFz9WG2F0Hm2kOURvTn/UwhmwNkEm4uPejFVIRsP4HMNmyUo1yLWzLIRJ+OAhiwbV86x3fLgbGhGU8VnKB9Fwfp5IR6SzZbjzbEFkxReOVafLWi0bjVKSN0QOmP6+8XKo9J8/Fg+VaJo0YE/aP1Kr+Zgt11XF7vggxSkVd4r4mBww8pkqPuRYQSXi/OoM0TuWBuHbFVFE26mDMj50o30VzfmBGl6ZzWWA7C1QTHxbk8KVX7i/gmE8s13DpzKmPVZLdtjA17ezg/Wy0mCzSbo8mJzhdke7FIQSi//6S3UAgN/hBFdVEd5S5K7T8ZWfGuUykdNsOXswWLxoZlKOfHOY/Mt7H9ax0ES5l03cnf9Gqls34XJ0MJB/9kSipNjgH655lMF00eENyTMAY/Q6DM9iZpWqwtt54lpooRJVJApmRsu2so8FFU24m5l5EHsPQ4FrwfHJzbf1mPc9cJgOKn4E63rM9HRM5LzVUqO+JW5iQepPvdsVakGnM8ZGnKS/HX4cpgC5d/hevdObfpgXmJi3XRo3emJBNOHKZTfqd7MMSm9JNJw7tc2BiLhHKmlIwFCVJ90DcXJeDw7jT/r8xj3M+tFurehS/oKd+KNYM+aeB+S4css8eEUn1iQO1zFmsIydyWl+Ch3bzoEco7Of/R/k0XUWcHB5N04WFxd4oZOMU9zxyxCd63ti4NLE6qWc8M7MTc0Qa1BYQIQkSxoKtwHZbfZTe7hWpErGp6PgBwubVdGpEF2rupuIhUDhP5iX37cX8AusdQQL
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: notifier-auth
  namespace: default
  labels:
    app.kubernetes.io/name: notifier
    app.kubernetes.io/instance: notifier
    app.kubernetes.io/managed-by: kubectl
spec:
  basicAuth:
    secret: notifier-auth
    removeHeader: true
